### ISSUE TITLE
Visual Studio build requires cmake 3.11+

### ISSUE THREAD

**Issue by donny-dont** [LibCMaker/ICU_CMake_Files#1]
Was trying to get a Visual Studio build going but hit this.

```
CMake Error at source/common_tools_exe_flags.cmake:36 (set_property):
  Error evaluating generator expression:

    $<COMPILE_LANGUAGE:CXX>

  $<COMPILE_LANGUAGE:...> may not be used with Visual Studio generators.
```

This was [addressed](https://gitlab.kitware.com/cmake/cmake/issues/17435) and it appears 3.11 is the minimum to do a Visual Studio build with these files.

There should probably be an error around this.

**Comment by NikitaFeodonit** [comment]
Yes, I checked and confirm that for Visual Studio it works only with version 3.11+.

According to [CMake 3.11 Release Notes / Generators](https://cmake.org/cmake/help/v3.12/release/3.11.html#generators), Visual Studio Generators was learned to support the COMPILE_LANGUAGE only from CMake 3.11.
